spring:
datasource:
  url: jdbc:h2:mem:testdb # Usa um banco de dados H2 em memória
  username: sa            # Usuário padrão do H2
  password:            # Senha padrão do H2
  driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true         # Habilita o console do H2
      path: /h2-console     # Caminho para acessar o console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update      # Atualiza o schema automaticamente com base nas entidades
    #    defer-datasource-initialization: true
    show-sql: true          # Exibe as queries SQL no console
    properties:
      hibernate:
        format_sql: true    # Formata as queries SQL para melhor legibilidade
  sql:
    init:
      mode: never          # Inicializa o banco de dados sempre que o aplicativo for iniciado

  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PUT, PATCH, DELETE
    allowed-headers: "*"
  messages:
    basename: i18n/messages
    encoding: UTF-8

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO