spring:
  application:
    name: expense tracker
  profiles:
    default: prod
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PUT, PATCH, DELETE
    allowed-headers: "*"
  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /expense-tracker

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always